apiVersion: v1
kind: Service
metadata:
  name: order-microservice
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 7200
      targetPort: 7200
      nodePort: 30003
  type: NodePort