apiVersion: v1
kind: Service
metadata:
  name: user-microservice
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30001
  type: NodePort
